[versions]
playwright = "1.58.0"
kotlinx-serialization = "1.7.1"
clikt = "3.4.0"
kotlinresult = "1.1.14"
logback = "1.5.16"
slf4j = "2.0.16"

[libraries]
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotlinresult = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinresult" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[bundles]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.3.0" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.3.0" }